---
experiment:
  name: tmn/utzappos/
dataset:
  data_dir: ut-zap50k
  dataset: utzappos
  splitname: compositional-split-natural
model_params:
  model: tmn
  emb_init: word2vec
  emb_dim: 300
  image_extractor: resnet18
  train_only: true
  static_inp: true
  num_negs: 600
  embed_rank: 64
  nmods: 24
training:
  batch_size: 256
  eval_val_every: 10
  load:
  lr: 0.0001
  lrg: 1.0e-06
  margin: 0.5
  max_epochs: 100
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 32
  test_set: val
  topk: 1
  wd: 5.0e-05
  workers: 8
  update_features: false
  freeze_features: false
(czsl) mmancini68@EML-Jupi