---
experiment:
  name: compcos_cw/mitstates
dataset:
  data_dir: mit-states
  dataset: mitstates
  splitname: compositional-split-natural
model_params:
  model: scen
  dropout: true
  norm: true
  nlayers: 2
  relu: false
  fc_emb: 768,1024,1200
  emb_dim: 600
  emb_init: ft+w2v
  image_extractor: resnet18
  train_only: true
  static_inp: false
training:
  seed: 6344
  batch_size: 128
  load:
  lr: 5.0e-05
  lrg: 0.001
  margin: 1.0
  cosine_scale: 20
  max_epochs: 150
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 64
  test_set: val
  topk: 1
  wd: 5.0e-05
  workers: 8
  update_features: false
  freeze_features: false
  epoch_max_margin: 15
  img_size: 512
  lambda_CE: 1.0
  lambda_aux: 1.0
  lambda_con: 51.0
  lambda_1: 0.2
